import type { Metadata } from "next";
import { Kanit } from 'next/font/google';
import Sidebar from "@/components/Sidebar";
const kanit = Kanit({
  weight: '300',
  subsets: ['latin', 'thai'],
});
export const metadata: Metadata = {
  title: "cit kmutt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/cmm.ico" />
      </head>
      <body
        className={kanit.className}
      >
        <div className="flex">
          <div className="w-52 bg-white text-blue-600 min-h-screen">
            <Sidebar />
          </div>
          <div className="w-full bg-gray-100">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
